# Simply execute 'make' to verify things still build

name: Build All

on:
  push:
    branches:
      - master
      - 'tr_*'

  # Allows running manually
  workflow_dispatch:
    inputs:
      use-latest-translations:
        required: false
        default: true
        description: 'Use latest translations from shared Google Docs sheet (default: true)'

jobs:
  build:
    runs-on: ubuntu-22.04
    container: docker://variantxyz/rgbds-20230123:e27da737c6aca9659458d95c32d606ebbea7380c

    steps:
      - name: List versions
        run: |
          git --version
          python3 --version
          rgbasm --version
          rgblink --version
          rgbgfx --version

      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          path: 'code'

      - name: Checkout baserom repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.BASEROM_REPOSITORY }}
          ssh-key: ${{ secrets.BASEROM_KEY }}
          path: 'baserom'

      - name: Copy baserom into main repository
        run: |
          cp $GITHUB_WORKSPACE/baserom/*.gbc $GITHUB_WORKSPACE/code

      - name: Get latest text from source
        if: github.event.inputs.use-latest-translations == 'true'
        working-directory: 'code'
        env:
          TRANSLATION_SHEET: sheet.xlsx
        run: |
          wget -q --no-check-certificate "${{ secrets.TRANSLATION_SHEET_URL_SOURCE }}" -O $TRANSLATION_SHEET
          make csv_from_xlsx

      - name: Make all
        working-directory: 'code'
        run: |
          make -j all

      - name: Generate IPS files
        working-directory: 'code'
        run: |
          ips_util create baserom_kabuto.gbc medarot4_kabuto.gbc -o m4kabuto-$GITHUB_RUN_NUMBER-$GITHUB_SHA.ips
          ips_util create baserom_kuwagata.gbc medarot4_kuwagata.gbc -o m4kuwagata-$GITHUB_RUN_NUMBER-$GITHUB_SHA.ips

      - name: 'Archive IPS files'
        uses: actions/upload-artifact@v2
        with:
          name: ips_files
          path: code/*.ips
          retention-days: 1

      - name: Verify there are no uncommitted changes
        if: github.event.inputs.use-latest-translations != 'true'
        working-directory: 'code'
        run: |
          [ -z "$(git status --porcelain)" ] && exit 0 || exit 1